Fix syntax error

diff --git a/debian/gcin-gtk-immodule.postinst.in b/debian/gcin-gtk-immodule.postinst.in
--- a/debian/gcin-gtk-immodule.postinst.in
+++ b/debian/gcin-gtk-immodule.postinst.in
@@ -11,7 +11,7 @@ if [ -x $GTK_QUERY_IMMODULES ]; then
             ;;
     esac
 else
-    echo "Cannot find $CMD" > &2
+    echo "Cannot find $CMD" >&2
 fi
 
 #DEBHELPER#
